name: template-file-action
description: |
  Creates a string using a liquid template and a JSON or YAML object, then 
  either creates a file or injects the result into an existing file.
author: DREST LTD
inputs:
  data:
    description: JSON or YAML object containing template data.
    required: true
  template:
    description: Liquid template.
    required: true
  target:
    description: Path of file to create or inject content into.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
